### ISSUE TITLE
Remove checked in dependencies?

### ISSUE THREAD

**Issue by liliakai** [phishdetect/phishdetect-extension#10]
It seems that css files from vex and tailwind are checked into the codebase. Should we instead be loading these from their respective node modules to make them easier to update and minimize our repo surface area?

**Comment by liliakai** [comment]
Also, same question for fontawesome css/js files.

**Comment by liliakai** [comment]
And again, with jquery and sha256 libraries in /lib!

**Comment by botherder** [comment]
However you think it's best. I moved e.g. jquery into a standalone file to avoid having it duplicated so often in the build versions of the various gmail.js, gui.js etc and because I was using it also in some popups.

As for fontawesome, I had the need to inject it on request because some pages were having some css collisions with it and I wanted to reduce the footprint on the webmail content script:
https://github.com/phishdetect/phishdetect-extension/blob/master/js/webmails.js#L51

**Comment by liliakai** [comment]
They'll still end up as standalone files in /build, just not tracked in the repo. See https://github.com/liliakai/phishdetect-extension/pull/1. You'll want to merge the webpack PR first.

**Comment by botherder** [comment]
Ah got it, that sounds good.
